language: go

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq memcached
    - memcached -p 11211 &
    - memcached -p 11212 &
    - go get -d -v ./...

script: go test -v ./...

go:
    - stable
